"""Added new table Journal and added [to_dict, __str__, __repr__] methods to User and Journal Models

Revision ID: 33459641fccf
Revises: 0808129ec4a6
Create Date: 2024-07-02 21:33:55.591048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33459641fccf'
down_revision = '0808129ec4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
